USE COMPANY;
SELECT CONCAT(E1.FNAME,' ',E1.MINIT,' ',E1.LNAME) AS FULL_NAME,E1.SSN,E1.DNO,COUNT(E2.SUPER_SSN) AS NUMBER_OF_EMPLOYEES FROM 
EMPLOYEE E1,EMPLOYEE E2 WHERE E1.SSN=E2.SUPER_SSN GROUP BY E2.SUPER_SSN;


