USE COMPANY;
SELECT D.DNUMBER,D.DNAME,COUNT(DL.DLOCATION) FROM DEPARTMENT D,DEPT_LOCATIONS DL WHERE D.DNUMBER=DL.DNUMBER AND D.MGR_SSN IN 
( SELECT ESSN FROM DEPENDENT WHERE SEX='F' GROUP BY ESSN HAVING COUNT(SEX) >= 2) GROUP BY D.DNUMBER;
